#!/usr/bin/env python3
"""Runs the asset converters that are out of date, then assembles the C-ROM.

C-ROM layout: tiles 0-255 are ngdevkit's eye-catcher logo, then each image set in SETS order. Global tile
numbers go into build/res/tile_bases.h (TILE_BASE_<NAME>) so the C data stays with local tile numbers.
Characters without art yet get a header that aliases Vorax, so the game always links."""
import glob, os, subprocess, sys
import numpy as np

sys.path.insert(0, os.path.dirname(__file__))
import neogfx as g

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "build", "res")
LOGO = os.path.join(ROOT, "assets", "ngdevkit", "base-crom-logo")
CHARACTERS = ["vorax", "zyra", "ossk", "grumm", "krell", "nyxa", "brutok", "koral", "xal"]
STAGES = ["temple", "sanctuary", "hive", "mine", "spaceport", "rooftops", "colosseum", "dome", "throne"]


def write_if_changed(path, data):
    """Keeps the timestamp when nothing changed, so make only recompiles what depends on real changes."""
    mode = "wb" if isinstance(data, bytes) else "w"
    if os.path.exists(path) and open(path, "rb" if mode == "wb" else "r").read() == data:
        return
    open(path, mode).write(data)


def mtime(path):
    return os.path.getmtime(path) if os.path.exists(path) else 0


def stale(outputs, inputs):
    newest_in = max((mtime(p) for p in inputs), default=0)
    return any(mtime(o) < newest_in for o in outputs)


def run(*args):
    print("+", " ".join(args[1:]))
    subprocess.run([sys.executable, *args], check=True, cwd=ROOT)


def tree(folder):
    out = []
    for base, _, files in os.walk(folder):
        out += [os.path.join(base, f) for f in files if f.endswith(".png")]
    return out


def main():
    os.makedirs(RES, exist_ok=True)
    tools = lambda *names: [os.path.join(ROOT, "tools", n) for n in (*names, "neogfx.py")]
    sets = [("fx", os.path.join(RES, "fx.tiles.npy"))]
    if stale([os.path.join(RES, "fx_data.h")], tools("make_fx.py") + tree(os.path.join(ROOT, "art", "gpt", "fx"))):
        run("tools/make_fx.py")
    if stale([os.path.join(RES, "screens_data.h")], tools("make_screens.py", "ui_art.py") + tree(os.path.join(ROOT, "art", "gpt", "screens")) + tree(os.path.join(ROOT, "art", "gpt", "story"))):
        run("tools/make_screens.py")
    sets.append(("screens", os.path.join(RES, "screens.tiles.npy")))
    if stale([os.path.join(RES, "crowd_data.h")], tools("make_crowd.py") + tree(os.path.join(ROOT, "art", "gpt", "crowd"))):
        run("tools/make_crowd.py")
    sets.append(("crowd", os.path.join(RES, "crowd.tiles.npy")))
    for s in STAGES:
        spec = os.path.join(ROOT, "data", f"stage_{s}.json")
        if stale([os.path.join(RES, f"stage_{s}.h")], tools("make_stage.py") + [spec]):
            run("tools/make_stage.py", s)
        sets.append((f"stage_{s}", os.path.join(RES, f"stage_{s}.tiles.npy")))
    real = []
    for c in CHARACTERS:
        spec = os.path.join(ROOT, "data", f"{c}.json")
        header = os.path.join(RES, f"{c}.h")
        if os.path.exists(spec):
            if stale([header], tools("make_fighter.py") + [spec] + tree(os.path.join(ROOT, "art", "gpt", c))):
                run("tools/make_fighter.py", c)
            sets.append((c, os.path.join(RES, f"{c}.tiles.npy")))
            real.append(c)
        else:
            alias = [f"/* {c}: no art yet, aliases vorax (tools/build_assets.py) */"]
            alias += [f"#define {c}_{k} vorax_{k}" for k in ("frames", "cells", "attrs", "steps", "anims", "palettes_p1", "palettes_p2")]
            write_if_changed(header, "\n".join(alias) + "\n")
    audio_in = [p for p in glob.glob(os.path.join(ROOT, "audio", "out", "*", "*.wav")) + glob.glob(os.path.join(ROOT, "audio", "out", "*", "*", "*.wav"))] + [os.path.join(ROOT, "tools", "make_sound.py")]
    if stale([os.path.join(RES, "sound_ids.h"), os.path.join(RES, "user_commands.s")], audio_in):
        run("tools/make_sound.py")
    fix = os.path.join(RES, "s1.fix")
    if stale([fix], tools("make_fix.py")):
        run("tools/make_fix.py", os.path.join(ROOT, "assets", "ngdevkit", "base-srom-text-shadow.fix"))

    # --- C-ROM
    c1 = bytearray(open(LOGO + ".c1", "rb").read())
    c2 = bytearray(open(LOGO + ".c2", "rb").read())
    base = len(c1) // 64
    lines = ["/* generated by tools/build_assets.py */", "#ifndef TILE_BASES_H", "#define TILE_BASES_H"]
    bank = g.TileBank()
    for name, path in sets:
        tiles = np.load(path)
        lines.append(f"#define TILE_BASE_{name.upper()} {base}  /* {len(tiles)} tiles */")
        bank.tiles = list(tiles)
        a, b = bank.crom()
        c1 += a
        c2 += b
        base += len(tiles)
    for c in CHARACTERS:
        if c not in real:
            lines.append(f"#define TILE_BASE_{c.upper()} TILE_BASE_VORAX")
    lines.append(f"#define TILES_TOTAL {base}")
    lines.append("#endif")
    write_if_changed(os.path.join(RES, "tile_bases.h"), "\n".join(lines) + "\n")
    size = 1 << 20
    while size < len(c1):
        size <<= 1
    write_if_changed(os.path.join(RES, "c1.bin"), bytes(c1) + bytes(size - len(c1)))
    write_if_changed(os.path.join(RES, "c2.bin"), bytes(c2) + bytes(size - len(c2)))
    write_if_changed(os.path.join(RES, "crom_size.mk"), f"CROMSIZE={size}\n")
    print(f"C-ROM: {base} tiles, {size // 1024} KB per chip")


if __name__ == "__main__":
    main()
