#!/usr/bin/env python3
"""Sound driver sources for nullsound (ngdevkit's Z80 driver).

  make_sound.py

From audio/out/a/<channel>/*.wav (ADPCM-A, 18500 Hz) and audio/out/b/*.wav (ADPCM-B music, 22050 Hz):
  build/res/sample-map.yaml   input for vromtool (V-ROM + offsets) and soundtool (commands)
  build/res/user_commands.s   the command jump table: 0-3 reserved, 4 stop music, one looping command
                              per music track, then the soundtool-generated sample commands
  build/res/sound_ids.h       game-side command numbers (SFX_*, VOICE_*, MUSIC_*)"""
import glob, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "build", "res")
MUSIC_RATE = 22050
STAGES = ["temple", "sanctuary", "hive", "mine", "spaceport", "rooftops", "colosseum", "dome", "boss"]
CHARACTERS = ["vorax", "zyra", "ossk", "grumm", "krell", "nyxa", "brutok", "koral", "xal"]


def ident(name):
    return name.replace("-", "_").lower()


def main():
    os.makedirs(RES, exist_ok=True)
    samples = []
    for path in sorted(glob.glob(os.path.join(ROOT, "audio", "out", "a", "*", "*.wav"))):
        samples.append(("adpcm_a", ident(os.path.splitext(os.path.basename(path))[0]), path, int(os.path.basename(os.path.dirname(path)))))
    music = []
    for path in sorted(glob.glob(os.path.join(ROOT, "audio", "out", "b", "*.wav"))):
        name = ident(os.path.splitext(os.path.basename(path))[0])
        music.append(name)
        samples.append(("adpcm_b", "music_" + name, path, None))

    lines = ["# generated by tools/make_sound.py"]
    for kind, name, path, channel in samples:
        lines.append(f"- {kind}:")
        if channel:
            lines.append(f"    channel: {channel}")
        lines.append(f"    name: {name}")
        lines.append(f"    uri: file://{path}")
    open(os.path.join(RES, "sample-map.yaml"), "w").write("\n".join(lines) + "\n")

    delta_n = round(MUSIC_RATE * 65536 / 55555)          # YM2610 ADPCM-B playback rate
    asm = [";;; generated by tools/make_sound.py", '        .include "helpers.inc"', '        .include "ym2610.inc"',
           '        .include "samples.inc"', '        .include "snd_commands.inc"', "        .area   CODE", "",
           "cmd_jmptable::", "        jp      snd_command_unused", "        jp      snd_command_01_prepare_for_rom_switch",
           "        jp      music_ngdevkit_eye_catcher", "        jp      snd_command_03_reset_driver",
           "        jp      music_stop"]
    asm += [f"        jp      loop_{n}" for n in music]
    asm += ["        generated_commands_jmptable_entries", "        init_unused_cmd_jmptable", "",
            "music_stop:", "        call    snd_adpcm_b_stop", "        ret", ""]
    for n in music:
        u = f"MUSIC_{n.upper()}"
        asm += [f"loop_{n}:", f"        ld      ix, #adpcm_b_{n}", "        call    snd_adpcm_b_play_loop", "        ret",
                f"adpcm_b_{n}:", f"        .db     {u}_START_LSB", f"        .db     {u}_START_MSB",
                f"        .db     {u}_STOP_LSB", f"        .db     {u}_STOP_MSB",
                f"        .dw     0x{delta_n:04x}          ; delta-n for {MUSIC_RATE} Hz", "        .db     0xc0             ; left+right",
                "        .db     0xb0             ; volume (leaves headroom for voices)", ""]
    asm += ["        generated_commands_implementation", ""]
    open(os.path.join(RES, "user_commands.s"), "w").write("\n".join(asm))

    names = {name for kind, name, _, _ in samples if kind == "adpcm_a"}

    def sfx(name):
        return f"SND_SFX_{name.upper()}" if name in names else "0"

    h = ["/* generated by tools/make_sound.py */", "#ifndef SOUND_IDS_H", "#define SOUND_IDS_H",
         f"#define _SND_CMD_BASE_GENERATED {5 + len(music)}", '#include "snd_commands.h"', "",
         "#define MUSIC_STOP 4"]
    for i, n in enumerate(music):
        h.append(f"#define MUSIC_{n.upper()} {5 + i}")
    stage_music = "MUSIC_TEMPLE" if "temple" in music else "0"
    track = lambda name, fallback: f"MUSIC_{name.upper()}" if name in music else fallback
    h += [f"#define MUSIC_TITLE_TRACK {track('title', stage_music)}", f"#define MUSIC_SELECT_TRACK {track('select', stage_music)}",
          f"#define MUSIC_BOSS_TRACK {track('boss', track('xal', stage_music))}", f"#define MUSIC_ENDING_TRACK {track('ending', track('title', stage_music))}",
          "static const u8 music_stage[9] = {" + ", ".join(track(st, stage_music) for st in STAGES) + "};"]
    plain = {
        "SFX_SWING_LIGHT": "swing_light", "SFX_SWING_HEAVY": "swing_heavy", "SFX_HIT_LIGHT": "hit_light",
        "SFX_HIT_HEAVY": "hit_heavy", "SFX_BLOCK": "block", "SFX_JUMP": "jump", "SFX_LAND": "land",
        "SFX_LAND_HEAVY": "land_heavy", "SFX_GRAB": "grab", "SFX_PROJECTILE": "projectile", "SFX_SUPER": "super",
        "SFX_COIN": "coin", "SFX_CURSOR": "cursor", "SFX_SELECT": "select", "SFX_VS": "vs", "SFX_COUNT": "count",
        "SFX_KO_BOOM": "ko_boom", "VOICE_KO": "ann_ko", "VOICE_ROUND1": "ann_round1", "VOICE_ROUND2": "ann_round2",
        "VOICE_FINAL": "ann_final", "VOICE_FIGHT": "ann_fight", "VOICE_PERFECT": "ann_perfect",
        "VOICE_TIMEOVER": "ann_timeover", "VOICE_YOUWIN": "ann_youwin", "VOICE_YOULOSE": "ann_youlose",
        "VOICE_DRAW": "ann_draw", "VOICE_CONTINUE": "ann_continue", "VOICE_GAMEOVER": "ann_gameover",
        "VOICE_TITLE": "ann_title", "VOICE_CHOOSE": "ann_choose", "SFX_TYPE": "type", "SFX_WARNING": "warning",
        "VOICE_XAL_INTRO": "xal_intro", "SFX_CROWD_CHEER": "crowd_cheer", "SFX_CROWD_OOH": "crowd_ooh",
        "SFX_CROWD_ROAR": "crowd_roar", "SFX_CROWD_APPLAUSE": "crowd_applause", "SFX_FIRE": "fire_burst",
        "VOICE_FIRST_ATTACK": "ann_first_attack", "VOICE_COUNTER": "ann_counter", "VOICE_REVERSAL": "ann_reversal",
    }
    for macro, name in plain.items():
        h.append(f"#define {macro} {sfx(name)}")
    for c in CHARACTERS:
        for line in ("special1", "special2", "super"):
            h.append(f"#define VOICE_{c.upper()}_{line.upper()} {sfx(c + '_' + line)}")
    for table, suffix in (("voice_hurt", "_hurt"), ("voice_win", "_win")):
        h.append(f"static const u8 {table}[9] = {{" + ", ".join(sfx(c + suffix) for c in CHARACTERS) + "};")
    h.append("static const u8 voice_name[9] = {" + ", ".join(sfx("ann_" + c) for c in CHARACTERS) + "};")
    h.append("static const u8 voice_story[4] = {" + ", ".join(sfx(f"story{i + 1}") for i in range(4)) + "};")
    h.append("#endif")
    open(os.path.join(RES, "sound_ids.h"), "w").write("\n".join(h) + "\n")
    print(f"sound: {len(samples) - len(music)} samples, {len(music)} music tracks")


if __name__ == "__main__":
    main()
