#!/usr/bin/env python3
"""GPT crowd sheets -> spectator sprites. Each sheet (art/gpt/crowd/<stage>.png) is a 4x2 grid: four
spectators watching (row 1) and the same four cheering (row 2), so frame 4 + k is the cheer of frame k.

  make_crowd.py

Writes build/res/crowd_data.h (one image set for all stages, 8 frames and 8 palettes per stage, in
STAGES order) and build/res/crowd.tiles.npy. Spectators are scaled to HEIGHT px, feet on the frame
bottom, x centered."""
import os, sys
import numpy as np
from PIL import Image

sys.path.insert(0, os.path.dirname(__file__))
import neogfx as g

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STAGES = ["temple", "sanctuary", "hive", "mine", "spaceport", "rooftops", "colosseum", "dome", "throne"]
HEIGHT = 46
PALETTES = 8


def cell(rgb, alpha, index):
    h, w = alpha.shape
    cx, cy = index % 4, index // 4
    y0, y1, x0, x1 = cy * h // 2, (cy + 1) * h // 2, cx * w // 4, (cx + 1) * w // 4
    a = alpha[y0:y1, x0:x1]
    ys, xs = np.nonzero(a > 0.5)
    return rgb[y0 + ys.min():y0 + ys.max() + 1, x0 + xs.min():x0 + xs.max() + 1], a[ys.min():ys.max() + 1, xs.min():xs.max() + 1]


def main():
    bank = g.TileBank()
    bank.add(np.zeros((16, 16), np.uint8))
    frames_out, cells_out, attrs_out, palette_words = [], [], [], []
    for stage in STAGES:
        path = os.path.join(ROOT, "art", "gpt", "crowd", stage + ".png")
        rgb = np.asarray(Image.open(path).convert("RGB")).astype(np.float64)
        corner = rgb[4, 4]
        key = (255, 0, 255) if corner[0] > 128 else (0, 255, 0)
        alpha = g.key_alpha(rgb, key)
        figs = [cell(rgb, alpha, i) for i in range(8)]
        # one scale per spectator so the watching and cheering poses match (the cheer is taller: arms up)
        frames = []
        for i, (c, a) in enumerate(figs):
            ref = figs[i % 4][1]
            s = HEIGHT / ref.shape[0]
            R, A = g.downscale(c, a, s)
            h, w = A.shape
            rows, cols = -(-h // 16), -(-w // 16)
            RR = np.zeros((rows * 16, cols * 16, 3)); AA = np.zeros((rows * 16, cols * 16))
            ox = (cols * 16 - w) // 2
            RR[rows * 16 - h:, ox:ox + w] = R; AA[rows * 16 - h:, ox:ox + w] = A
            frames.append((RR, AA, rows, cols))
        tiles = []
        for fi, (R, A, rows, cols) in enumerate(frames):
            for r in range(rows):
                for c in range(cols):
                    a = A[r * 16:(r + 1) * 16, c * 16:(c + 1) * 16]
                    if (a > 0.5).any():
                        tiles.append((fi, r, c, R[r * 16:(r + 1) * 16, c * 16:(c + 1) * 16][a > 0.5]))
        palettes, assign = g.build_palettes([t[3] for t in tiles], PALETTES, rounds=3)
        grids = [np.zeros((rows, cols, 2), np.int32) for _, _, rows, cols in frames]
        for (fi, r, c, _), p in zip(tiles, assign):
            R, A = frames[fi][:2]
            grid = g.map_to_palette(R[r * 16:(r + 1) * 16, c * 16:(c + 1) * 16], A[r * 16:(r + 1) * 16, c * 16:(c + 1) * 16], palettes[p])
            t, flip = bank.add(grid)
            grids[fi][r, c] = (t, p | flip << 4)
        for (R, A, rows, cols), grid in zip(frames, grids):
            frames_out.append(f"    {{{-(cols * 8)}, {-(rows * 16)}, {cols}, {rows}, {len(cells_out)}, {{0, 0, 0, 0}}, {{0, 0, 0, 0}}}},")
            for c in range(cols):
                for r in range(rows):
                    cells_out.append(int(grid[r, c, 0])); attrs_out.append(int(grid[r, c, 1]))
        for pal in palettes:
            palette_words += [0x8000] + [g.packed15(col) for col in pal] + [0] * (15 - len(pal))
        while len(palette_words) % (PALETTES * 16):
            palette_words += [0x8000] + [0] * 15
    out = os.path.join(ROOT, "build", "res")
    os.makedirs(out, exist_ok=True)
    np.save(os.path.join(out, "crowd.tiles.npy"), np.array(bank.tiles, np.uint8))
    lines = ["/* generated by tools/make_crowd.py */", "#ifndef CROWD_DATA_H", "#define CROWD_DATA_H",
             f"#define CROWD_PALETTES {PALETTES}", "#define CROWD_FRAMES_PER_STAGE 8",
             "static const u16 crowd_cells[] = {" + ",".join(map(str, cells_out)) + "};",
             "static const u8 crowd_attrs[] = {" + ",".join(map(str, attrs_out)) + "};",
             "static const Frame crowd_frames[] = {\n" + "\n".join(frames_out) + "\n};",
             "static const u16 crowd_palettes[] = {" + ",".join(f"0x{w:04x}" for w in palette_words) + "};",
             "#endif"]
    open(os.path.join(out, "crowd_data.h"), "w").write("\n".join(lines) + "\n")
    print(f"crowd: {len(frames_out)} frames, {len(bank.tiles)} tiles")


if __name__ == "__main__":
    main()
