#!/usr/bin/env python3
"""GPT stage painting -> Neo Geo stage: 3 bands (sky, middle, floor) with their own scroll speed.

  make_stage.py temple

data/stage_<name>.json: {"image", "scale", "width", "bands": [[y0, y1, speed16], x3], "ground", "palettes",
"crowd" (spectator set, null = none), "crowd_feet" (row of the painted barrier base), "particle", "motion"}
Band rows are in scaled pixels and must be multiples of 16. A band scrolling at speed s/16 only needs
320 + (width - 320) * s / 16 pixels, cut from the center of the painting, so far layers stay centered.

Writes build/res/stage_<name>.h, build/res/stage_<name>.tiles.npy, preview/stage_<name>.png."""
import json, os, sys
import numpy as np
from PIL import Image

sys.path.insert(0, os.path.dirname(__file__))
import neogfx as g

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main(name):
    spec = json.load(open(os.path.join(ROOT, "data", f"stage_{name}.json")))
    src = Image.open(os.path.join(ROOT, "art", "gpt", spec["image"])).convert("RGB")
    scaled = src.resize((round(src.width * spec["scale"]), round(src.height * spec["scale"])), Image.LANCZOS)
    rgb = np.asarray(scaled).astype(np.float64)
    width = spec["width"]
    bands = []
    for y0, y1, speed in spec["bands"]:
        need = 320 + (width - 320) * speed // 16 + 16    # 21 sprite columns past the last scroll step
        cols = -(-need // 16)
        x0 = (rgb.shape[1] - cols * 16) // 2
        assert x0 >= 0, f"painting too narrow for band {y0}-{y1}: needs {cols * 16}px"
        bands.append({"rgb": rgb[y0:y1, x0:x0 + cols * 16], "cols": cols, "rows": (y1 - y0) // 16, "y": y0, "speed": speed})

    cells = []
    for bi, b in enumerate(bands):
        for r in range(b["rows"]):
            for c in range(b["cols"]):
                cells.append((bi, r, c, b["rgb"][r * 16:(r + 1) * 16, c * 16:(c + 1) * 16].reshape(-1, 3)))
    palettes, assign = g.build_palettes([c[3] for c in cells], spec["palettes"], rounds=3)

    bank = g.TileBank()
    bank.add(np.zeros((16, 16), np.uint8))
    grids = [np.zeros((b["rows"], b["cols"], 2), np.int32) for b in bands]
    preview = [np.zeros((b["rows"] * 16, b["cols"] * 16, 3)) for b in bands]
    full = np.ones((16, 16))
    for (bi, r, c, _), p in zip(cells, assign):
        tile_rgb = bands[bi]["rgb"][r * 16:(r + 1) * 16, c * 16:(c + 1) * 16]
        grid = g.map_to_palette(tile_rgb, full, palettes[p])
        tile, flip = bank.add(grid)
        grids[bi][r, c] = (tile, p | flip << 4)
        preview[bi][r * 16:(r + 1) * 16, c * 16:(c + 1) * 16] = np.vstack([np.zeros((1, 3)), palettes[p]])[grid]

    out_dir = os.path.join(ROOT, "build", "res"); os.makedirs(out_dir, exist_ok=True)
    np.save(os.path.join(out_dir, f"stage_{name}.tiles.npy"), np.array(bank.tiles, np.uint8))
    cells_out, attrs_out, frames = [], [], []
    for b, grid in zip(bands, grids):
        frames.append(f"    {{0, {b['y']}, {b['cols']}, {b['rows']}, {len(cells_out)}, {{0, 0, 0, 0}}, {{0, 0, 0, 0}}}},")
        for c in range(b["cols"]):
            for r in range(b["rows"]):
                cells_out.append(int(grid[r, c, 0])); attrs_out.append(int(grid[r, c, 1]))
    words = []
    for pal in palettes:
        words += [0x8000] + [g.packed15(col) for col in pal] + [0] * (15 - len(pal))
    top = rgb[0:16].reshape(-1, 3).mean(0)
    # glow: the most saturated bright colors pulse (lava, neon, lanterns, crystals)
    import colorsys
    scored = []
    for pi, pal in enumerate(palettes):
        for ci, col in enumerate(pal):
            h, s, v = colorsys.rgb_to_hsv(*(np.array(col) / 255.0))
            if s > 0.45 and v > 0.7:
                scored.append((s * v, pi * 16 + ci + 1))
    glow = [k for _, k in sorted(scored, reverse=True)[:14]]
    motions = {"drift": 0, "rise": 1, "fall": 2, "twinkle": 3}
    lines = [f"/* generated by tools/make_stage.py from data/stage_{name}.json */",
             f"#define STAGE_{name.upper()}_TILES {len(bank.tiles)}",
             f"static const u16 stage_{name}_cells[] = {{" + ",".join(map(str, cells_out)) + "};",
             f"static const u8 stage_{name}_attrs[] = {{" + ",".join(map(str, attrs_out)) + "};",
             f"static const Frame stage_{name}_frames[] = {{\n" + "\n".join(frames) + "\n};",
             f"static const u16 stage_{name}_palettes[] = {{" + ",".join(f"0x{w:04x}" for w in words) + "};",
             f"static const u16 stage_{name}_glow[] = {{" + ",".join(map(str, glow or [0])) + "};",
             f"const Stage stage_{name} = {{{{stage_{name}_frames, stage_{name}_cells, stage_{name}_attrs, TILE_BASE_STAGE_{name.upper()}}}, "
             f"stage_{name}_palettes, {len(palettes)}, {width}, {bands[-1]['y'] + bands[-1]['rows'] * 16}, {spec['ground']}, "
             "{" + ", ".join(f"{{{i}, {b['speed']}, {b['y']}}}" for i, b in enumerate(bands)) + "}, "
             f"0x{g.packed15(g.to_neo(top)):04x}, {255 if spec.get('crowd') is None else spec['crowd']}, {spec.get('crowd_feet', spec['ground'] - 32)}, FXA_{spec.get('particle', 'P_STAR')}, {motions[spec.get('motion', 'drift')]}, "
             f"stage_{name}_glow, {len(glow)}}};"]
    open(os.path.join(out_dir, f"stage_{name}.h"), "w").write("\n".join(lines) + "\n")

    # preview: each band at camera center, stacked
    img = Image.new("RGB", (max(b["cols"] for b in bands) * 16, sum(b["rows"] for b in bands) * 16), (0, 0, 0))
    y = 0
    for b, pv in zip(bands, preview):
        img.paste(Image.fromarray(pv.astype(np.uint8)), ((img.width - pv.shape[1]) // 2, y))
        y += pv.shape[0]
    os.makedirs(os.path.join(ROOT, "preview"), exist_ok=True)
    img.resize((img.width * 2, img.height * 2), Image.NEAREST).save(os.path.join(ROOT, "preview", f"stage_{name}.png"))
    print(f"stage {name}: {len(bank.tiles)} tiles, {len(palettes)} palettes, bands {[b['cols'] for b in bands]}")


if __name__ == "__main__":
    main(sys.argv[1])
