/* The roster: art data generated by tools/make_fighter.py plus each character's moves. */
#include "fighter.h"
#include "sound.h"
#include "fx.h"
#include "tile_bases.h"

#include "vorax.h"
#include "zyra.h"
#include "ossk.h"
#include "grumm.h"
#include "krell.h"
#include "nyxa.h"
#include "brutok.h"
#include "koral.h"
#include "xal.h"

#define PUNCHES (BTN_A | BTN_C)
#define KICKS (BTN_B | BTN_D)

#define IMAGES(n, N) {n##_frames, n##_cells, n##_attrs, TILE_BASE_##N}
#define ART(n, N) IMAGES(n, N), n##_steps, n##_anims, n##_palettes_p1, n##_palettes_p2

/* move: motion, buttons, kind, damage, hits, speed_x, speed_y, invulnerable, projectile fx, voice */
const Character characters[CHARACTER_COUNT] = {
    {"VORAX", ART(vorax, VORAX), 8, 2, 105,
     {"236", PUNCHES, MOVE_PROJECTILE, 30, 1, 4, 0, 0, FXA_PROJ_VORAX, VOICE_VORAX_SPECIAL1},
     {"623", PUNCHES, MOVE_RISING, 36, 2, 0, 8, 10, 0, VOICE_VORAX_SPECIAL2},
     {"236236", PUNCHES, MOVE_RUSH, 22, 5, 5, 0, 30, 0, VOICE_VORAX_SUPER},
     0, 0, 100},
    {"ZYRA", ART(zyra, ZYRA), 10, 0, 90,
     {"236", PUNCHES, MOVE_PROJECTILE, 26, 1, 5, 0, 0, FXA_PROJ_ZYRA, VOICE_ZYRA_SPECIAL1},
     {"623", KICKS, MOVE_RISING, 32, 3, 0, 9, 12, 0, VOICE_ZYRA_SPECIAL2},
     {"236236", PUNCHES, MOVE_BEAM, 90, 1, 7, 0, 30, FXA_PROJ_ZYRA, VOICE_ZYRA_SUPER},
     1, 1, 100},
    {"OSSK", ART(ossk, OSSK), 11, 0, 85,
     {"214", KICKS, MOVE_RUSH, 12, 3, 6, 0, 0, 0, VOICE_OSSK_SPECIAL1},
     {"623", PUNCHES, MOVE_RISING, 34, 2, 0, 10, 10, 0, VOICE_OSSK_SPECIAL2},
     {"236236", KICKS, MOVE_RUSH, 20, 6, 7, 0, 30, 0, VOICE_OSSK_SUPER},
     2, 2, 100},
    {"GRUMM", ART(grumm, GRUMM), 6, 3, 125,
     {"236", PUNCHES, MOVE_PROJECTILE, 34, 1, 3, 0, 0, FXA_PROJ_GRUMM, VOICE_GRUMM_SPECIAL1},
     {"214", PUNCHES, MOVE_RUSH, 30, 1, 5, 0, 6, 0, VOICE_GRUMM_SPECIAL2},
     {"236236", PUNCHES, MOVE_GRAB, 100, 1, 4, 0, 30, 0, VOICE_GRUMM_SUPER},
     3, 3, 100},
    {"KRELL", ART(krell, KRELL), 9, 2, 100,
     {"236", PUNCHES, MOVE_PROJECTILE, 28, 1, 6, 0, 0, FXA_PROJ_KRELL, VOICE_KRELL_SPECIAL1},
     {"214", KICKS, MOVE_RUSH, 30, 1, 7, 0, 4, 0, VOICE_KRELL_SPECIAL2},
     {"236236", PUNCHES, MOVE_BEAM, 100, 1, 8, 0, 30, FXA_PROJ_KRELL, VOICE_KRELL_SUPER},
     4, 4, 100},
    {"NYXA", ART(nyxa, NYXA), 11, 0, 88,
     {"236", PUNCHES, MOVE_PROJECTILE, 22, 1, 6, 0, 0, FXA_PROJ_NYXA, VOICE_NYXA_SPECIAL1},
     {"623", KICKS, MOVE_RISING, 30, 2, 0, 10, 10, 0, VOICE_NYXA_SPECIAL2},
     {"236236", KICKS, MOVE_RUSH, 20, 6, 8, 0, 30, 0, VOICE_NYXA_SUPER},
     5, 5, 100},
    {"BRUTOK", ART(brutok, BRUTOK), 6, 3, 128,
     {"236", PUNCHES, MOVE_PROJECTILE, 32, 1, 4, 0, 0, FXA_PROJ_BRUTOK, VOICE_BRUTOK_SPECIAL1},
     {"214", PUNCHES, MOVE_RUSH, 18, 3, 4, 0, 0, 0, VOICE_BRUTOK_SPECIAL2},
     {"236236", PUNCHES, MOVE_GRAB, 110, 1, 4, 0, 30, 0, VOICE_BRUTOK_SUPER},
     6, 6, 100},
    {"KORAL", ART(koral, KORAL), 10, 1, 95,
     {"236", PUNCHES, MOVE_PROJECTILE, 26, 1, 5, 0, 0, FXA_PROJ_KORAL, VOICE_KORAL_SPECIAL1},
     {"623", PUNCHES, MOVE_RISING, 32, 3, 0, 9, 12, 0, VOICE_KORAL_SPECIAL2},
     {"236236", PUNCHES, MOVE_BEAM, 95, 1, 7, 0, 30, FXA_PROJ_KORAL, VOICE_KORAL_SUPER},
     7, 7, 100},
    {"XAL", ART(xal, XAL), 9, 1, 120,
     {"236", PUNCHES, MOVE_PROJECTILE, 32, 1, 5, 0, 0, FXA_PROJ_XAL, VOICE_XAL_SPECIAL1},
     {"214", KICKS, MOVE_TELEPORT, 0, 0, 0, 0, 20, 0, VOICE_XAL_SPECIAL2},
     {"236236", PUNCHES, MOVE_BEAM, 110, 1, 6, 0, 30, FXA_PROJ_XAL, VOICE_XAL_SUPER},
     8, 8, 150},
};
