/* Story text: attract intro, select screen bios, win quotes, the boss intro and each ending.
 * Lines fit the fix layer (38 visible columns); select bios fit the 19 columns right of the bust. */
#include "story.h"

const char *const intro_text[INTRO_PAGES][3] = {
    {"THE YEAR 3099.", "THE MOTHERSHIP NEXUS HAS DRAINED", "A THOUSAND WORLDS."},
    {"ITS MASTER, XAL THE OVERMIND,", "FEEDS ON THE STRONGEST MINDS", "IN THE GALAXY."},
    {"HE SUMMONS EVERY WORLD TO THE", "XENO TOURNAMENT. THE CHAMPION", "WINS FREEDOM FOR THEIR PLANET."},
    {"THE DEFEATED LOSE THEIR MINDS.", "", "EIGHT WARRIORS ANSWER THE CALL."},
};

const char *const epithet[CHARACTER_COUNT] = {
    "WARLORD OF DRAKKON", "PSYCHIC OF LYR", "HIVE ASSASSIN", "TITAN OF MAGMOR",
    "BOUNTY HUNTER", "SHADOW OF 2 MOONS", "PIT CHAMPION", "TIDE PRINCESS", "THE OVERMIND",
};

const char *const bio[CHARACTER_COUNT][3] = {
    {"THE NEXUS TOOK HIS", "TRIBE. HE CAME TO", "TAKE THEM BACK."},
    {"HER SISTERS' MINDS", "SCREAM INSIDE THE", "OVERMIND."},
    {"BETRAYED BY HIS", "QUEEN, HE FIGHTS", "TO RULE THE HIVE."},
    {"XAL STRIPS HIS", "WORLD OF ITS", "LIVING CRYSTAL."},
    {"THE BIGGEST BOUNTY", "IN THE GALAXY HAS", "ONE NAME: XAL."},
    {"A CLAN ASSASSIN", "WITH A SECRET", "CONTRACT."},
    {"UNBEATEN IN 900", "FIGHTS. HE WANTS", "ONE MORE."},
    {"THE NEXUS DRINKS", "THE OCEANS OF", "HER HOMEWORLD."},
    {"MASTER OF THE", "NEXUS.", ""},
};

const char *const win_quote[CHARACTER_COUNT][2] = {
    {"YOUR BONES WILL DECORATE", "MY TEMPLE!"},
    {"I SAW EVERY MOVE BEFORE", "YOU EVEN THOUGHT OF IT."},
    {"SSSILENT. SSSWIFT.", "YOU NEVER SSSAW ME."},
    {"ROCK... CRUSHES...", "EVERYTHING."},
    {"NOTHING PERSONAL.", "YOU WERE JUST IN MY WAY."},
    {"THE SHADOWS CHOSE ME.", "NOT YOU."},
    {"WHO IS NEXT?!", "BRUTOK IS STILL HUNGRY!"},
    {"THE TIDE ALWAYS", "RETURNS."},
    {"YOUR MIND BELONGS", "TO ME NOW."},
};

const char *const boss_text[BOSS_PAGES][2] = {
    {"SO... YOU ARE THE ONE WHO", "BROKE MY TOURNAMENT."},
    {"YOUR MIND WILL BE", "MY FINEST TROPHY."},
};

const char *const ending_text[PLAYABLE_COUNT][ENDING_PAGES][2] = {
    {{"THE OVERMIND FELL. HIS CROWN", "SHATTERED IN VORAX'S CLAWS."},
     {"THE TRIBES OF DRAKKON CAME HOME", "AND SANG OF THEIR WARLORD."},
     {"BUT DEEP IN THE JUNGLE, THE", "SHARDS STILL WHISPER..."}},
    {{"WITH XAL GONE, A THOUSAND", "STOLEN MINDS WERE FREE."},
     {"ZYRA GUIDED THEM HOME, LIGHT", "BY LIGHT, ACROSS THE STARS."},
     {"THE SANCTUARY OF LYR WILL", "NEVER BE SILENT AGAIN."}},
    {{"OSSK RETURNED WITH THE", "OVERMIND'S CROWN."},
     {"THE QUEEN WHO BETRAYED HIM", "WAS NEVER SEEN AGAIN."},
     {"THE HIVE BOWED.", "LONG LIVE THE HIVE KING."}},
    {{"GRUMM TORE THE NEXUS CHAINS", "FROM THE HEART OF MAGMOR."},
     {"THE CRYSTAL SONG ROSE AGAIN", "FROM THE LAVA."},
     {"THE TITAN SLEEPS NOW.", "HE HAS EARNED IT."}},
    {{"THE NEXUS BURNED BEHIND HIM.", "KRELL DID NOT LOOK BACK."},
     {"THE BOUNTY: ONE BILLION", "CREDITS. A GALAXY RECORD."},
     {"SOMEWHERE, A NEW CONTRACT", "IS ALREADY WAITING."}},
    {{"NYXA TOOK THE OVERMIND'S", "BRAIN CRYSTAL FOR HER CLAN."},
     {"HER CONTRACT WAS NEVER TO", "KILL XAL..."},
     {"...BUT TO STEAL HIS POWER.", "THE TWO MOONS SMILE."}},
    {{"THE PITS OF GORR SHOOK WITH", "THE ROAR OF A MILLION FANS."},
     {"BRUTOK, CHAMPION OF THE", "GALAXY, RAISED THE BELT."},
     {"\"WHO IS NEXT?!\" HE SHOUTED.", "NOBODY ANSWERED."}},
    {{"AS THE NEXUS FELL, THE STOLEN", "OCEANS RAINED ON HER WORLD."},
     {"KORAL RODE THE GREAT LEVIATHAN", "HOME, AND HER PEOPLE SANG."},
     {"THE TIDE PRINCESS BECAME", "THE TIDE QUEEN."}},
};
